# Generated by Django 5.2 on 2025-04-03 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensiontransaction',
            name='pensioner',
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pension_type', models.CharField(choices=[('Old Age', 'Old Age'), ('Disability', 'Disability'), ('Family', 'Family')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=20)),
                ('pensioner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pensions.pensioner')),
            ],
        ),
        migrations.AddField(
            model_name='pensiontransaction',
            name='pension',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pensions.pension'),
            preserve_default=False,
        ),
    ]
