# Generated by Django 5.2 on 2025-04-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0002_remove_pensiontransaction_pensioner_pension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='force_password_reset',
            field=models.BooleanField(default=True),
        ),
    ]
