# Generated by Django 5.2 on 2025-04-03 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0003_grievance_updated_at_user_force_password_reset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pensioner',
            old_name='aadhar_number',
            new_name='aadhaar_number',
        ),
        migrations.AlterField(
            model_name='grievance',
            name='pensioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pensions.pensioner'),
        ),
        migrations.AlterField(
            model_name='lifecertificate',
            name='pensioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pensions.pensioner'),
        ),
    ]
