# Generated by Django 5.2 on 2025-04-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0004_rename_aadhar_number_pensioner_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
