# Generated by Django 4.2.20 on 2025-04-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0006_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='subject',
            field=models.CharField(choices=[('Pension not credited', 'Pension not credited'), ('Incorrect pension amount', 'Incorrect pension amount'), ('Life certificate issue', 'Life certificate issue'), ('Bank detail update', 'Bank detail update'), ('Document verification delay', 'Document verification delay'), ('Other', 'Other')], max_length=255),
        ),
    ]
