# Generated by Django 4.2.20 on 2025-04-10 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0007_alter_grievance_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensiontransaction',
            name='pension',
        ),
        migrations.AddField(
            model_name='pensiontransaction',
            name='pensioner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pensions.pensioner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pensiontransaction',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pensiontransaction',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pensiontransaction',
            name='transaction_date',
            field=models.DateField(),
        ),
    ]
