# Generated by Django 4.2.20 on 2025-04-10 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0008_remove_pensiontransaction_pension_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensiontransaction',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='pensiontransaction',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='pensiontransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pensiontransaction',
            name='month',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pensiontransaction',
            name='status',
            field=models.CharField(choices=[('Credited', 'Credited'), ('Pending', 'Pending')], max_length=20),
        ),
    ]
