# Generated by Django 4.2.20 on 2025-04-10 04:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0009_remove_pensiontransaction_remarks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifecertificate',
            old_name='document',
            new_name='certificate',
        ),
        migrations.AddField(
            model_name='lifecertificate',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lifecertificate',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Submitted', max_length=10),
        ),
        migrations.AlterField(
            model_name='lifecertificate',
            name='pensioner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pensions.pensioner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lifecertificate',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
