# Generated by Django 4.2.20 on 2025-04-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0010_rename_document_lifecertificate_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifecertificate',
            name='live_photo',
            field=models.ImageField(blank=True, null=True, upload_to='live_photos/'),
        ),
    ]
