# Generated by Django 4.2.20 on 2025-04-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0011_lifecertificate_live_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.AlterField(
            model_name='lifecertificate',
            name='live_photo',
            field=models.ImageField(blank=True, null=True, upload_to='life_certificates/photos/'),
        ),
    ]
