# Generated by Django 4.2.20 on 2025-04-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0012_announcement_alter_lifecertificate_live_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
